---
- name: PowerDNS installation
  become: yes
  hosts: powerdns
  tasks:
    - name: install mysql from remote repo
      yum: 
        name: https://repo.mysql.com/mysql80-community-release-el7-3.noarch.rpm
        state: present
    - name: import GPG key
      ansible.builtin.rpm_key:
        state: present
        key: https://repo.mysql.com/RPM-GPG-KEY-mysql-2022
    - name: install mysql package
      yum:
        name: mysql-community-server
        state: present
    - name: install mysql python
      yum:
        name: MySQL-python
        state: present
    - name: setting mysql service on levels 2,3,5
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes
    - name: Changing Auth methods
      lineinfile: 
        path: /etc/my.cnf
        line: 'default-authentication-plugin=mysql_native_password'
        insertbefore: datadir=/var/lib/mysql*
      register: trigger
    - name: restart mysql service
      ansible.builtin.service:
        name: mysqld
        state: restarted
    - name: get temp root password
      shell: "grep 'A temporary password is generated for root@localhost' /var/log/mysqld.log | awk -F ' ' '{print $(NF)}' | tail -1"
      register: root_password
      when: trigger.changed
    - name: update expired root password
      ansible.builtin.command: mysql --user root --password={{ root_password.stdout }} --connect-expired-password --execute="ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_root_password }}';"
      when: trigger.changed
    - name: install from remote repo
      yum:
        name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
        state: present
    - name: install pdns
      yum:
        name:
          - pdns
          - pdns-backend-mysql
        state: present
    - name: creating root with creds for database 
      template:
        src: my.cnf.j2
        dest: /root/.my.cnf
        owner: root 
        mode: 0600
      notify: Restart MySQL
    - name: restart mysql
      ansible.builtin.service:
        name: mysqld
        state: restarted
    - name: creating database for powerdns
      mysql_db:
        login_unix_socket: /var/lib/mysql/mysql.sock
        login_password: "{{ mysql_root_password }}"
        login_user: root
        name: powerdns
    - name: creating pdns mysql user
      mysql_user: 
        login_unix_socket: /var/lib/mysql/mysql.sock
        login_password: "{{ mysql_root_password }}"
        login_user: root
        name: pdns
        password: "{{ pdns_password }}"
        state: present
    - name: copying database file over
      copy:
        src: domains.sql
        dest: /tmp/domains.sql
    - name: importing into database
      mysql_db:
        login_unix_socket: /var/lib/mysql/mysql.sock
        login_password: "{{ mysql_root_password }}"
        login_user: root
        name: powerdns 
        state: import
        target: /tmp/domains.sql  
    
